# Generated by Django 3.2 on 2022-08-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transmit', '0004_auto_20220821_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicstate',
            old_name='session_id',
            new_name='session',
        ),
    ]
