# Generated by Django 3.2 on 2022-09-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmit', '0007_alter_sensorstate_locationupdate_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorstate',
            old_name='angularVelocity_length',
            new_name='angular_velocity_length',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='angularVelocity_x',
            new_name='angular_velocity_x',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='angularVelocity_y',
            new_name='angular_velocity_y',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='angularVelocity_z',
            new_name='angular_velocity_z',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='headingMagnetic_north',
            new_name='heading_magnetic_north',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='locationUpdate_time',
            new_name='location_update_time',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='magneticField_length',
            new_name='magnetic_field_length',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='magneticField_x',
            new_name='magnetic_field_x',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='magneticField_y',
            new_name='magnetic_field_y',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='magneticField_z',
            new_name='magnetic_field_z',
        ),
        migrations.RenameField(
            model_name='sensorstate',
            old_name='orientation_isIdentity',
            new_name='orientation_is_identity',
        ),
        migrations.RemoveField(
            model_name='musicstate',
            name='repeatMode',
        ),
        migrations.AddField(
            model_name='musicstate',
            name='repeat_mode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
