# Generated by Django 3.2 on 2022-08-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "album_image",
                    models.ImageField(blank=True, upload_to="music/images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "artist_image",
                    models.ImageField(blank=True, upload_to="music/images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250)),
                ("genre", models.CharField(blank=True, max_length=250)),
                (
                    "energy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Too Negative", "Too Negative"),
                            ("Negative", "Negative"),
                            ("Neutral", "Neutral"),
                            ("Positive", "Positive"),
                            ("Too Positive", "Too Positive"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "valence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Too Negative", "Too Negative"),
                            ("Negative", "Negative"),
                            ("Neutral", "Neutral"),
                            ("Positive", "Positive"),
                            ("Too Positive", "Too Positive"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "song_image",
                    models.ImageField(blank=True, upload_to="music/images/"),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True)),
                ("address", models.FileField(blank=True, upload_to="")),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musics",
                        to="player.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musics",
                        to="player.artist",
                    ),
                ),
            ],
        ),
    ]
