# Generated by Django 3.2 on 2022-08-20 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("acceleration_x", models.FloatField(blank=True, null=True)),
                ("accelerationY", models.FloatField(blank=True, null=True)),
                ("accelerationZ", models.FloatField(blank=True, null=True)),
                ("accelerationLength", models.FloatField(blank=True, null=True)),
                ("pressureHectoPascal", models.FloatField(blank=True, null=True)),
                ("headingMagneticNorth", models.FloatField(blank=True, null=True)),
                ("locationUpdateTime", models.DateTimeField(blank=True, null=True)),
                ("locationLatitude", models.FloatField(blank=True, null=True)),
                ("locationLongitude", models.FloatField(blank=True, null=True)),
                ("locationAltitude", models.FloatField(blank=True, null=True)),
                ("locationAccuracy", models.FloatField(blank=True, null=True)),
                ("locationVerticalAccuracy", models.FloatField(blank=True, null=True)),
                ("locationSpeed", models.FloatField(blank=True, null=True)),
                ("locationCourseTrueNorth", models.FloatField(blank=True, null=True)),
                (
                    "locationIsFromMockProvider",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "locationAltitudeRefrenceSystem",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("angularVelocityX", models.FloatField(blank=True, null=True)),
                ("angularVelocityY", models.FloatField(blank=True, null=True)),
                ("angularVelocityZ", models.FloatField(blank=True, null=True)),
                ("angularVelocityLength", models.FloatField(blank=True, null=True)),
                ("magneticFieldX", models.FloatField(blank=True, null=True)),
                ("magneticFieldY", models.FloatField(blank=True, null=True)),
                ("magneticFieldZ", models.FloatField(blank=True, null=True)),
                ("magneticFieldLength", models.FloatField(blank=True, null=True)),
                ("orientationX", models.FloatField(blank=True, null=True)),
                ("orientationY", models.FloatField(blank=True, null=True)),
                ("orientationZ", models.FloatField(blank=True, null=True)),
                ("orientationW", models.FloatField(blank=True, null=True)),
                ("orientationLength", models.FloatField(blank=True, null=True)),
                ("orientationIsIdentity", models.BooleanField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transmit.session",
                    ),
                ),
            ],
        ),
    ]
